#!/usr/bin/env bash

function gvm_implode() {
  read -p "Are you sure? [Y/n] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   display_message "Action cancelled"
 else
   (rm -rf "$GVM_ROOT" && display_message "GVM successfully removed") || display_error "Failed to uninstall gvm"
 fi
}
