language: c

env:
  global:
  - SRC_REPO=$TRAVIS_BUILD_DIR
  - GVM_NO_GIT_BAK=1
  - GVM_NO_UPDATE_PROFILE=1

before_install:
  - binscripts/gvm-installer $TRAVIS_COMMIT $TRAVIS_BUILD_DIR/tmp

install:
  - gem install tf -v '>=0.4.1'

script:
  - source $TRAVIS_BUILD_DIR/tmp/gvm/scripts/gvm; rake default scenario

matrix:
  include:
    - name: "Mojave build"
      osx_image: xcode11
    - name: "High Sierra build"
      osx_image: xcode10.1
    - name: "Sierra build"
      osx_image: xcode9.2
    - name: "Linux build"
      os: linux
      dist: xenial
    - name: "Linux Bionic build"
      os: linux
      dist: bionic
    - name: "Linux Xenial build"
      os: linux
      dist: xenial
    - name: "Linux Trusty build"
      os: linux
      dist: trusty
