#!/bin/bash
GVM_DEST=~
ENV_FILE=~/.bashrc
SRC_REPO=git://github.com/jbussdieker/gvm.git

if [ -d $GVM_DEST/.gvm ]; then
  echo "Already installed!"
else
  cd $GVM_DEST && git clone $SRC_REPO .gvm > /dev/null 2>&1

  cat ~/.bashrc | grep "\[\[ -s \"\$HOME/.gvm/scripts/gvm\" ]] && source \"\$HOME/.gvm/scripts/gvm\"" > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo '[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"' >> $ENV_FILE
  fi

  echo "Installed GVM v$GVM_VERSION"
fi
