#!/usr/bin/env bash

# source once and only once!
[[ ${GVM_SHELL_COMPAT:-} -eq 1 ]] && return || readonly GVM_SHELL_COMPAT=1

# force zsh to start arrays at index 0
# [[ -n $ZSH_VERSION ]] && setopt KSH_ARRAYS

# __gvm_is_function()
# /*!
# @abstract Returns whether or not a named function exists in the shell.
# @param func_name Name of the function to check
# @return Returns success (status 0) if the named function exists or failure
#   (status 1).
# */
__gvm_is_function() {
    local func_name="${1}"

    [[ "x${func_name}" == "x" ]] && return 1

    # using 'declare -f' is the most reliable way for both bash and zsh!
    builtin declare -f "${1}" >/dev/null

    return $?
}

__gvm_callstack() {
    local index=${1}

    if [[ "x${BASH_VERSION}" != "x" ]]; then
        echo "${FUNCNAME[index]}"
    elif [[ "x${ZSH_VERSION}" != "x" ]]; then
        echo "${FUNCNAME[index+1]}"
    else
        echo "unknown caller"
        return 1
    fi

    return 0
}

# __gvm_rematch()
# /*!
# @abstract Provide a cross-platform regex rematcher.
# @discussion
# This function implements consistent regex rematch functionality for bash and
#   zsh shells. The result is similar to the output expected using the '=~'
#   pattern match operator in bash: matching results will be written to an array
#   stored in the var_name provided or 'GVM_REMATCH' (the default).
#
# Rematch results can be accessed beginning with index 1: GVM_REMATCH[1] and
#   subsequent matches (if any) appear in later indexes. The match at index 1
#   consists of the entire matched string while later matches are related to
#   specified capture groups noted in the regex pattern.
# @param string The string to match against the regex pattern
# @param regex The regex pattern
# @param var_name [optional] The name of the variable into which the resulting
#   rematch array will be set.
# @return Returns success (status 0) if the string matches the regex pattern,
#   otherwise failure (status 1).
# */


__gvm_rematch() {
    if [[ -n $ZSH_VERSION ]]; then
        setopt KSH_ARRAYS
        setopt BASH_REMATCH
    fi

    local string="${1}"; shift
    local regex="${1}"; shift
    local var_name="${1:-GVM_REMATCH}"
    local rematch_ary; rematch_ary=()

    if [[ ${#string} -eq 0 ]];then
        if [[ -n $ZSH_VERSION ]]; then
            unsetopt KSH_ARRAYS
            unsetopt BASH_REMATCH
        fi
        return 1
    fi
    if [[ ${#regex} -eq 0 ]]; then
        if [[ -n $ZSH_VERSION ]]; then
            unsetopt KSH_ARRAYS
            unsetopt BASH_REMATCH
        fi
        return 1
    fi

    # perform regex - same on bash and ksh
    [[ "${string}" =~ $regex ]]
    if [[ $? -ne 0 ]];then
        if [[ -n $ZSH_VERSION ]]; then
            unsetopt KSH_ARRAYS
            unsetopt BASH_REMATCH
        fi
        return 1
    fi
    # support bash and zsh
    #
    # NOTE: 'setopt KSH_ARRAYS' must be set for zsh to force array indexes to
    # start at 0, like bash.
    #
    rematch_ary+=( "${BASH_REMATCH[@]}" )

    if [[ "${var_name}" != "$" ]]; then
        # assign to passed var
        eval "${var_name}=( \"\${rematch_ary[@]}\" )"
    fi

    if [[ -n $ZSH_VERSION ]]; then
        unsetopt KSH_ARRAYS
        unsetopt BASH_REMATCH
    fi
    return 0
}
