#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

command=$1
if [[ -f $GVM_ROOT/scripts/alias-$command ]]; then
	shift
  "$GVM_ROOT/scripts/alias-$command" "$@"
elif [[ -n $command ]]; then
  display_fatal "Unrecognized command line argument: '$command'"
else
  echo "= gvm alias

* http://github.com/moovweb/gvm

== DESCRIPTION:

GVM alias is used to manage go version aliases

== Usage

  gvm alias Command

== Command

  create     - create a new alias
  delete     - delete an alias
  list       - list aliases"
fi

