#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

error_message=""

# Check for git
command -v git &> /dev/null ||
	error_message="${error_message}
Could not find git

  ubuntu: apt-get install mercurial
  mac:   brew install mercurial
"
# Check for ar
command -v ar &> /dev/null ||
	error_message="${error_message}
Could not find binutils

  ubuntu: apt-get install binutils
"
# Check for bison
command -v bison &> /dev/null ||
	error_message="${error_message}
Could not find bison

  ubuntu: apt-get install bison
  fedora: dnf install bison bison-devel
"
# Check for gcc
command -v gcc &> /dev/null ||
	error_message="${error_message}
Could not find gcc

  ubuntu: apt-get install gcc
"
# Check for make
command -v make &> /dev/null ||
	error_message="${error_message}
Could not find make

  ubuntu: apt-get install make
"
# Check for curl
command -v curl &> /dev/null ||
	error_message="${error_message}
Could not find curl

  ubuntu: apt-get install curl
  mac:   brew install curl
"

if [ -n "$error_message" ]; then
	display_warning "$error_message"
	exit 1
else
	# All good!
	exit 0
fi
