#!/bin/bash
if [[ $1 == "pkg" ]] && [[ $2 == "uninstall" ]]; then
  if [[ "$3" == "" ]]; then
    echo "ERROR: Please specify the package name"
    exit 1
  fi

  UNINSTALL_ROOT=$GVM_ROOT/pkgs/pkg.gvm/$3
  if [[ ! -d $UNINSTALL_ROOT ]]; then
    echo "ERROR: Invalid package name"
    exit 1
  fi

  if [[ "$4" != "" ]]; then
    UNINSTALL_ROOT=$UNINSTALL_ROOT/$4
  fi

  if [[ -d $UNINSTALL_ROOT ]]; then
    rm -rf $UNINSTALL_ROOT
  else
    echo "ERROR: Invalid package version"
    exit 1
  fi

  if [[ "$4" != "" ]]; then
    echo "Uninstalled $3 version $4"
  else
    echo "Uninstalled $3"
  fi
else
  echo "Please use gvm [action] to call this file"
  exit 1
fi

