#!/bin/bash
display_error() {
	tput sgr0
	tput setaf 1
	echo "ERROR: $1" >&2
	tput sgr0
	exit 1
}

[ -z `which hg` ] &&
  display_error '* Could not find mercurial (try `sudo apt-get install mercurial`)'
[ -z `which ar` ] &&
  display_error '* Could not find binutils (try `sudo apt-get install binutils (or binutils-multiarch)`)'
[ -z `which bison` ] &&
  display_error '* Could not find bison (try `sudo apt-get install bison`)'
[ -z `which gcc` ] &&
  display_error '* Could not find gcc (try `sudo apt-get install gcc`)'
[ -z `which make` ] &&
  display_error '* Could not find make (try `sudo apt-get install make`)'

exit 0
