#!/bin/bash
. $GVM_ROOT/scripts/functions

echo
display_message "gvm gos (installed)"
echo
if [ -d $GVM_ROOT/gos ]; then
	if [[ "$gvm_go_name" != "" ]]; then
		ls -1 $GVM_ROOT/gos | sed 's/^/   /g' | sed 's/^   '$gvm_go_name'/=> '$gvm_go_name'/g'
	else
		ls -1 $GVM_ROOT/gos | sed 's/^/   /g'
	fi
fi
echo

