#!/bin/bash
command=$1
if [ -f $GVM_ROOT/scripts/pkg-$command ]; then
	shift
  $GVM_ROOT/scripts/pkg-$command $@
elif [[ -n $command ]]; then
  echo "ERROR: Unrecognized command line argument: '$command'"
else
  echo "= gvm pkg

* http://github.com/moovweb/gvm

== DESCRIPTION:

GVM Package is used to manage various Go packages

== Usage

  gvm pkg Command

== Command

  install    - install go packages
  uninstall  - uninstall go packages
  list       - list installed go packages"
fi

