#!/bin/bash
. $GVM_ROOT/scripts/display_error

echo "
gvm packages $gvm_go_name@$gvm_pkgset_name"
echo
for package in $GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/pkg.gvm/*; do
  if [ $package == "$GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/pkg.gvm/*" ]; then
    break
  fi
  package_name=`echo $package | awk '{ n=split($1,path,"/"); print path[n] }'`
  output=$package_name" ("
  first=true
  for version in $package/*; do
    version=`echo $version | awk '{ n=split($1,path,"/"); print path[n] }'`
    if [ "$version" != "current" ]; then
      if [ $first == true ]; then
        first=false
      else
        output=$output", "
      fi
      version=`echo $version | awk '{ n=split($1,path,"/"); print path[n] }'`
      output=$output$version
    fi
  done
  output=$output")"

  echo $output
done
echo

