#!/bin/bash
display_error() {
	tput sgr0
	tput setaf 1
	echo "ERROR: $1"
	tput sgr0
	exit 1
}

[[ "$1" == "" ]] && 
	display_error "Please specify package name"

gvm_go_path=$GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name

UNINSTALL_ROOT=$gvm_go_path/pkg.gvm/$1
if [[ ! -d $UNINSTALL_ROOT ]]; then
  echo "ERROR: Invalid package name"
  exit 1
fi

if [[ "$2" != "" ]]; then
  UNINSTALL_ROOT=$UNINSTALL_ROOT/$2
fi

if [[ -d $UNINSTALL_ROOT ]]; then
  rm -rf $UNINSTALL_ROOT
else
  echo "ERROR: Invalid package version"
  exit 1
fi

if [[ "$4" != "" ]]; then
  echo "Uninstalled $1 version $2"
else
  echo "Uninstalled $1"
fi

