#!/bin/bash
. $GVM_ROOT/scripts/display_error

[[ $gvm_pkgset_name != "" ]] || 
	display_error "No Package set selected"
rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/* ||
  display_error "Could not delete package set files"

