#!/bin/bash
CUR_VER=`readlink $GVM_ROOT/go | awk '{ n=split($1,path,"/"); print path[n] }'`
if [[ $CUR_VER == "" ]]; then
	echo "ERROR: No Go version selected"
	exit 1
else
  if [ -e $GVM_ROOT/pkgsets/$CUR_VER/$1 ]; then
	  rm -f $GVM_ROOT/pkgs
	  ln -s $GVM_ROOT/pkgsets/$CUR_VER/$1 $GVM_ROOT/pkgs
	else
		echo "ERROR: Invalid package set name"
		exit 1
	fi
fi

