#!/bin/bash
. $GVM_ROOT/scripts/display_error

[[ $gvm_go_name != "" ]] || 
	display_error "No Go version selected"

[[ $1 != "" ]] || 
	display_error "Please specifiy the name"

[[ -d $GVM_ROOT/pkgsets/$gvm_go_name/$1 ]] || 
	display_error "Packageset doesn't exist!"

rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$1 ||
	display_error "Could not delete package set"

rm -rf $GVM_ROOT/environments/$gvm_go_name@$1 ||
	display_error "Could not delete package set"

