#!/bin/bash
display_error() {
	tput sgr0
	tput setaf 1
	echo "ERROR: $1"
	tput sgr0
	exit 1
}

[[ $gvm_go_name != "" ]] || 
	display_error "No Go version selected"
. $GVM_ROOT/enviroments/$gvm_go_name@$1 ||
	print_error "Invalid package set"

