#!/bin/bash
if [[ -n $1 ]]; then
	CUR_VER=`readlink $GVM_ROOT/go | awk '{ n=split($1,path,"/"); print path[n] }'`
	if [[ $CUR_VER == "" ]]; then
		echo "ERROR: No Go version selected"
		exit 1
	else
    mkdir -p $GVM_ROOT/pkgsets/$CUR_VER/$1
    if [[ $? -ne 0 ]]; then
			echo "ERROR: Could not create folder"
			exit 1
		fi
	fi
else
  echo "ERROR: Please specifiy the name"
  exit 1
fi

