#!/bin/bash
. $GVM_ROOT/scripts/functions

[[ $1 != "" ]] || 
	display_error "Please specifiy the name"

[[ ! -f "$GVM_ROOT/enviroments/$gvm_go_name@$1" ]] || 
	display_error "Packageset already exists!"

mkdir -p $GVM_ROOT/pkgsets/$gvm_go_name/$1 ||
	display_error "Could not create folder"
cp $GVM_ROOT/environments/$gvm_go_name $GVM_ROOT/environments/$gvm_go_name@$1 ||
	display_error "Could copy environment"
echo "export gvm_pkgset_name=\"$1\"" >> $GVM_ROOT/environments/$gvm_go_name@$1 ||
	display_error "Could not extend environment"
echo "export GOPATH; GOPATH=\"$GVM_ROOT/pkgsets/release.r60.3/$1:\$GOPATH\"" >> $GVM_ROOT/environments/$gvm_go_name@$1 ||
	display_error "Could not extend environment"
echo "export PATH; PATH=\"$GVM_ROOT/pkgsets/release.r60.3/$1/bin:\$PATH\"" >> $GVM_ROOT/environments/$gvm_go_name@$1 ||
	display_error "Could not extend environment"

