#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

[[ $gvm_go_name != "" ]] ||
	display_fatal "No Go version selected"
[[ -d $GVM_ROOT/gos/$gvm_go_name ]] ||
	display_fatal "Invalid or corrupt Go version"
[[ -d $GVM_ROOT/pkgsets/$gvm_go_name ]] ||
	display_fatal "Missing package set folder for this Go version"

command=$1
if [[ -f $GVM_ROOT/scripts/pkgset-$command ]]; then
	shift
  "$GVM_ROOT/scripts/pkgset-$command" "$@"
elif [[ -n $command ]]; then
  display_fatal "Unrecognized command line argument: '$command'"
else
  echo "= gvm pkgset

* http://github.com/moovweb/gvm

== DESCRIPTION:

GVM pkgset is used to manage various Go packages

== Usage

  gvm pkgset Command

== Command

  create     - create a new package set
  delete     - delete a package set
  use        - select where gb and goinstall target and link
  empty      - remove all code and compiled binaries from package set
  list       - list installed go packages"
fi

