#!/bin/bash
if [[ $gvm_go_name == "" ]]; then
  echo "ERROR: No Go version selected"
  exit 1
fi

if [[ -n $1 ]]; then
  mkdir -p $GVM_ROOT/pkgsets/$gvm_go_name/$1
  if [[ $? -ne 0 ]]; then
		echo "ERROR: Could not create folder"
		exit 1
	fi
else
  echo "ERROR: Please specifiy the name"
  exit 1
fi

