#!/bin/bash
go_version=`readlink $GVM_ROOT/go | awk '{ n=split($1,path,"/"); print path[n] }'`
pkgset=`readlink $GVM_ROOT/pkgs | awk '{ n=split($1,path,"/"); print path[n] }'`
if [[ -n $1 ]]; then
	if [[ "$1" == "g" ]]; then
		echo $go_version
	elif [[ "$1" == "ps" ]]; then
		echo $pkgset
	fi
else
	echo $go_version@$pkgset
fi

