#!/bin/bash
if [[ -n $1 ]]; then
  fuzzy_match=`ls $GVM_ROOT/gos | grep "$1"`
  if [[ $? != 0 ]]; then
    echo "Invalid version $1"
    exit 1
  fi
  if [ -d $GVM_ROOT/gos/$fuzzy_match ]; then
    CUR_VER=`readlink $GVM_ROOT/go | awk '{ n=split($1,path,"/"); print path[n] }'`
    if [[ "$CUR_VER" == "$fuzzy_match" ]]; then
      rm -rf $GVM_ROOT/go
      rm -rf $GVM_ROOT/pkgs
    fi
    rm -rf $GVM_ROOT/gos/$fuzzy_match
    rm -rf $GVM_ROOT/pkgsets/$fuzzy_match
		rm -f $GVM_ROOT/environments/$fuzzy_match
		rm -f "$GVM_ROOT/environments/$fuzzy_match@"*
    echo "Uninstalled version $fuzzy_match"
  else
    echo "Invalid version"
    exit 1
  fi
  exit 0
else
  echo "ERROR: Please specifiy the version"
  exit 1
fi

