#!/bin/bash
. $GVM_ROOT/scripts/functions

cd $GVM_ROOT/archive/go &> /dev/null ||
	display_fatal "Failed to find local Go source"

cd $GVM_ROOT/archive/go && hg pull ||
	display_fatal "Failed to update"

