#!/bin/bash
if [[ -n $1 ]]; then
  fuzzy_match=`ls $GVM_ROOT/gos | grep "$1"`
  if [[ $? != 0 ]]; then
    echo "Invalid version $1"
    exit 1
  fi
  if [ -d $GVM_ROOT/gos/$fuzzy_match ]; then
    rm -f $GVM_ROOT/go
    ln -s $GVM_ROOT/gos/$fuzzy_match $GVM_ROOT/go
    rm -f $GVM_ROOT/pkgs
    ln -s $GVM_ROOT/pkgsets/$fuzzy_match/default $GVM_ROOT/pkgs
  else
    echo "Invalid version $1"
    exit 1
  fi
else
  echo "ERROR: Please specifiy the version"
  exit 1
fi
echo "Now using version $fuzzy_match"

